version: '2'

services:
    fhem:
        expose:
            - "8083"
            - "7072"
            - "51826"
        ports:
            - "8083:8083"
            - "7072:7072"
            - "51826:51826"
        build: fhem
        privileged: true
        stdin_open: true
        tty: true
        networks:
            - code-network
#       devices:
        volumes:
            - ./fhem/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./fhem/start.sh:/opt/fhem/start.sh
            - /docker/fhem_recover/fhem.cfg:/opt/fhem/fhem.cfg
            - /docker/fhem_recover/FHEM/99_myUtils.pm:/opt/fhem/FHEM/99_myUtils.pm
            - ./fhem/data/Abfallkalender/muellkalender.ics:/opt/data/muellkalender.ics
            - ./fhem/fhem_recover/contrib/dblog/db.conf:/opt/fhem/contrib/dblog/db.conf
#           - ./fhem/data/controls.txt:/opt/fhem/controls.txt
#           - /docker/fhem_recover/fhem/data/controls.txt:/opt/fhem/controls.txt
#           - ./fhem/data/FHEM/99_myUtils.pm:/opt/fhem/FHEM/99_myUtils.pm
#           - ./fhem/log/:/opt/fhem/log
#           - ./fhem/data/fhem.cfg:/opt/fhem/fhem.cfg
        depends_on:
            - "mysql"


    mysql:
        expose:
            - "3306"
            - "33060"
        ports:
            - "3306:3306"
            - "33060:33060"
        image: mysql/mysql-server:5.7
#        privileged: true
#        stdin_open: true
        tty: true
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
            - code-network
#       devices:
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
            - ./mysql/data:/var/lib/mysql

#        depends_on:


networks:
    code-network:
        driver: bridge    
