version: '2'

services:
    fhem:
        restart: always
        expose:
            - "8083"
            - "7072"
        ports:
            - "8083:8083"
            - "7072:7072"
        build: fhem
        privileged: true
        volumes:
            - ./fhem/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./fhem/start.sh:/opt/fhem/start.sh
            - ./fhem/data/Abfallkalender/muellkalender.ics:/opt/data/muellkalender.ics
            - /docker/fhem_recover/:/opt/fhem/
            - /docker/backup:/opt/fhem/backup
        networks:
            - jarvis-network
        depends_on:
            - "mysql"

    homebridge:
        restart: always
        image: oznu/homebridge
        volumes:
            - ./homebridge/config.json:/homebridge/config.json
            - ./homebridge/package.json:/homebridge/package.json
        environment:
            - TZ=Europe/Berlin
            - PGID=1000
            - PUID=1000
        network_mode: host
        depends_on:
            - "fhem"

    mysql:
        restart: always
        expose:
            - "3306"
            - "33060"
        ports:
            - "3306:3306"
            - "33060:33060"
        image: mysql/mysql-server:5.7
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
            - /docker/mysql_recover/data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
            - jarvis-network

networks:
    jarvis-network:
        driver: bridge    
