version: '3'

services:
    fhem:
        expose:
            - "8083"
            - "7072"
            - "51826"
        ports:
            - "8083:8083"
            - "7072:7072"
            - "51826:51826"
        build: fhem
        privileged: true
        stdin_open: true
        tty: true
        networks:
            - code-networks
#       devices:
        volumes:
            - ./fhem/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./fhem/start.sh:/opt/fhem/start.sh
            - /docker/fhem_recover/fhem.cfg:/opt/fhem/fhem.cfg
            - /docker/fhem_recover/FHEM/99_myUtils.pm:/opt/fhem/FHEM/99_myUtils.pm
            - ./fhem/data/Abfallkalender/muellkalender.ics:/opt/data/muellkalender.ics

#           - ./fhem/data/contrib/dblog/db.conf:/opt/fhem/contrib/dblog/db.conf
#           - ./fhem/data/controls.txt:/opt/fhem/controls.txt
#           - /docker/fhem_recover/fhem/data/controls.txt:/opt/fhem/controls.txt
#           - ./fhem/data/FHEM/99_myUtils.pm:/opt/fhem/FHEM/99_myUtils.pm
#           - ./fhem/log/:/opt/fhem/log
#           - ./fhem/data/fhem.cfg:/opt/fhem/fhem.cfg
#        depends_on:

networks:
    code-network:
        driver: bridge    
